export const items =  [
    {
      id: 1,
      category: 'mobiles',
      title: "Apple iPhone 14",
      imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3PuckZp',
      description: 'Apple iPhone 14 (128 GB) - Blue',
      price: '89999',
    },
    {
      id: 2,
      category: 'mobiles',
      title: "Apple iPhone 11",
      imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/44MiYi6',
      description: 'Apple iPhone 11 (64GB) - White',
      price: '79999',
    },
{
      id: 3,
      category: 'mobiles',
      title: "Apple iPhone 13",
      imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3r6XJtv',
      description: 'Apple iPhone 13 (128GB) - Blue',
      price: '69999',
    },
    {
      id: 4,
      category: 'mobiles',
      title: "Samsung Galaxy S23 Ultra",
      imgSrc: '/img/s23.jpg',
      amazonLink: 'https://amzn.to/3cMb7vQ',
      description: 'Samsung Galaxy S23 Ultra 5G (256GB) - Phantom Black',
      price: '124999',
    },
    {
      id: 5,
      category: 'mobiles',
      title: "OnePlus 11 5G",
      imgSrc: '/img/oneplus-11.webp',
      amazonLink: 'https://amzn.to/3t4vHM8',
      description: 'OnePlus 11 5G (128GB) - Titan Black',
      price: '54999',
    },
    {
      id: 6,
      category: 'mobiles',
      title: "Xiaomi 13 Pro",
      imgSrc: '/img/xiaomi-13.jpg',
      amazonLink: 'https://amzn.to/3JOD8hx',
      description: 'Xiaomi 13 Pro (256GB) - Ceramic White',
      price: '74999',
    },
    {
      id: 7,
      category: 'mobiles',
      title: "Google Pixel 8 Pro",
      imgSrc: '/img/g-pixel.jpeg',
      amazonLink: 'https://amzn.to/3LG3j6k',
      description: 'Google Pixel 8 Pro (128GB) - Obsidian',
      price: '99999',
    },
    {
      id: 8,
      category: 'mobiles',
      title: "Samsung Galaxy Z Flip 5",
      imgSrc: '/img/z-fold.jpg',
      amazonLink: 'https://amzn.to/45kDbBO',
      description: 'Samsung Galaxy Z Flip 5 5G (256GB) - Graphite',
      price: '99999',
    },
    {
      id: 9,
      category: 'mobiles',
      title: "Motorola Edge 40",
      imgSrc: '/img/moto-edge.webp',
      amazonLink: 'https://amzn.to/3Xqww1n',
      description: 'Motorola Edge 40 (256GB) - Nebula Green',
      price: '35999',
    },
    {
      id: 10,
      category: 'mobiles',
      title: "Realme 11 Pro+ 5G",
      imgSrc: '/img/realme-11pro.webp',
      amazonLink: 'https://amzn.to/45vcftz',
      description: 'Realme 11 Pro+ 5G (256GB) - Sunrise Beige',
      price: '28999',
    },
    {
      id: 11,
      category: 'mobiles',
      title: "Vivo V27 Pro",
      imgSrc: '/img/vivo-v27.png',
      amazonLink: 'https://amzn.to/3PKVd4V',
      description: 'Vivo V27 Pro (256GB) - Magic Blue',
      price: '37999',
    },
    {
      id: 12,
      category: 'mobiles',
      title: "Oppo Reno 10 Pro 5G",
      imgSrc: '/img/reno-10.jpg',
      amazonLink: 'https://amzn.to/3L5iwU3',
      description: 'Oppo Reno 10 Pro 5G (256GB) - Glossy Purple',
      price: '39999',
    },
    {
      id: 13,
      category: 'mobiles',
      title: "Realme Narzo 60 5G",
      imgSrc: '/img/narzo-60.webp',
      amazonLink: 'https://amzn.to/3t74HF7',
      description: 'Realme Narzo 60 5G (128GB) - Cosmic Purple',
      price: '19999',
    },
    {
      id: 14,
      category: 'tablets',
      title: "Xiaomi Pad 6",
      imgSrc: '/img/ipad-9gen.webp',
      amazonLink: 'https://amzn.to/3ZeNRdY',
      description: 'Xiaomi Pad 6| Qualcomm Snapdragon 870| ',
      price: '29999',
    },
    {
      id: 15,
      category: 'tablets',
      title: "Lenovo Tab P12 Pro AMOLED",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3RabsdH',
      description: 'Lenovo Tab P12 Pro AMOLED (12.6 inch (32 cm), 8 GB, 256 GB, Wi-fi Only), Storm Grey with Precision Pen 3',
      price: '19999',
    },
    {
      id: 16,
      category: 'tablets',
      title: "Samsung Galaxy Tab A8",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3Pdsh4F',
      description: 'Samsung Galaxy Tab A8 26.69cm (10.5 inch) Display, RAM 4 GB, ROM 64 GB Expandable, Wi-Fi Tablet, Gray, (SM-X200NZAEINU)',
      price: '49999',
    },
    {
      id: 17,
      category: 'tablets',
      title: "Apple iPad 10.2-inch (9th Gen)",
      imgSrc: '/img/ipad2-9gen.webp',
      amazonLink: 'https://amzn.to/3POy95w',
      description: 'Apple iPad 10.2-inch (9th Gen) Wi-Fi + Cellular, 64GB, Space Gray (2021)',
      price: '31990',
    },
    {
      id: 18,
      category: 'tablets',
      title: "Lenovo Tab P11 Pro",
      imgSrc: '/img/lenovo-tab.webp',
      amazonLink: 'https://amzn.to/3PquWwf',
      description: 'Lenovo Tab P11 Pro 11.5-inch 2K OLED, RAM 6 GB, ROM 128 GB, Android Tablet with Dolby Vision, Keyboard Compatibility, Slate Grey',
      price: '25999',
    },
    {
      id: 19,
      category: 'tablets',
      title: "Samsung Galaxy Tab S6 Lite",
      imgSrc: '/img/samsung-tab-s6.jpg',
      amazonLink: 'https://amzn.to/3LjdwnX',
      description: 'Samsung Galaxy Tab S6 Lite 10.4" Display, S Pen Included, RAM 4 GB, ROM 64 GB, Wi-Fi, Angora Blue',
      price: '25990',
    },
    {
      id: 20,
      category: 'tablets',
      title: "Apple iPad Pro 11-inch (2022)",
      imgSrc: '/img/ipad-11.webp',
      amazonLink: 'https://amzn.to/3R0Khg3',
      description: 'Apple iPad Pro 11-inch (2022) Wi-Fi + Cellular, M2 Chip, 128GB, Space Gray, 120Hz Display',
      price: '73900',
    },
    {
      id: 21,
      category: 'tablets',
      title: "Fire HD 10 Tablet (2021)",
      imgSrc: '/img/fire-hd.jpg',
      amazonLink: 'https://amzn.to/3PHFY4m',
      description: 'Fire HD 10 Tablet (2021) - 10.1" 1080p Full HD Display, 32 GB Storage, 3 GB RAM, 12-hour Battery, Black',
      price: '12999',
    },
    {
      id: 22,
      category: 'tablets',
      title: "Huawei MatePad Pro 12.6",
      imgSrc: '/img/huwai-tab.webp',
      amazonLink: 'https://amzn.to/3RL7xU9',
      description: 'Huawei MatePad Pro 12.6" Tablet, 8GB RAM, 256GB Storage, Kirin 990, 4K Display, Wi-Fi, Silver Frost',
      price: '71999',
    },
    {
      id: 23,
      category: 'tablets',
      title: "Microsoft Surface Pro 7",
      imgSrc: '/img/microsoft-tab.jpg',
      amazonLink: 'https://amzn.to/3rsFw7Z',
      description: 'Microsoft Surface Pro 7 12.3" Touchscreen, Intel Core i5, 8GB RAM, 128GB SSD, Platinum',
      price: '74990',
    },
    {
      id: 24,
      category: 'tablets',
      title: "Realme Pad X",
      imgSrc: '/img/realme-pad-x.jpg',
      amazonLink: 'https://amzn.to/3Tof1F7',
      description: 'Realme Pad X 10.95-inch, 6GB RAM, 128GB Storage, 8400mAh, 4G LTE, Glacier Blue',
      price: '22999',
    },
    {
      id: 25,
      category: 'tablets',
      title: "Lenovo Yoga Tab 11",
      imgSrc: '/img/lenovo-yoga.jpeg',
      amazonLink: 'https://amzn.to/3Tof6hR',
      description: 'Lenovo Yoga Tab 11 11-inch Display, 4GB RAM, 128GB Storage, Dolby Atmos, Android Tablet, Storm Gray',
      price: '22990',
    },
    {
      id: 26,
      category: 'tablets',
      title: "Acer Iconia One 10",
      imgSrc: '/img/acer-iconia.jpeg',
      amazonLink: 'https://amzn.to/3LhjFv1',
      description: 'Acer Iconia One 10 (2021) 10.1-inch Display, 3GB RAM, 32GB Storage, Wi-Fi, Black',
      price: '15999',
    },
    {
      id: 27,
      category: 'laptops',
      title: "Lenovo IdeaPad Slim 5 ",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/44JsK4r',
      description: 'Lenovo IdeaPad Slim 5 Intel Core i5 12450H 14" (35.5cm) ',
      price: '29999',
    },
    {
      id: 28,
      category: 'laptops',
      title: "Apple MacBook Air Laptop",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina Display, ',
      price: '89999',
    },
    {
      id: 29,
      category: 'laptops',
      title: "Xiaomi [Smartchoice] Notebookpro",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3EzeQaC',
      description: 'Xiaomi [Smartchoice] Notebookpro ',
      price: '49999',
    },
    {
      id: 30,
      category: 'laptops',
      title: "HP Spectre x360",
      imgSrc: '/img/hp-spectre.webp',
      amazonLink: 'https://amzn.to/3ZAZZZw',
      description: 'HP Spectre x360 13.3-inch 4K OLED Touchscreen Laptop, Intel Core i7, 16GB RAM, 512GB SSD, Windows 10, Nightfall Black',
      price: '149999',
    },
    {
      id: 31,
      category: 'laptops',
      title: "Lenovo ThinkPad X1 Carbon",
      imgSrc: '/img/lenovo-thinkpad.webp',
      amazonLink: 'https://amzn.to/3r91jAN',
      description: 'Lenovo ThinkPad X1 Carbon Gen 9 14-inch FHD, Intel Core i7, 16GB RAM, 512GB SSD, Windows 10, Black',
      price: '141999',
    },
    {
      id: 32,
      category: 'laptops',
      title: "Asus ROG Zephyrus G14",
      imgSrc: '/img/asus-rog.jpg',
      amazonLink: 'https://amzn.to/3OBGq4O',
      description: 'Asus ROG Zephyrus G14 14-inch FHD Gaming Laptop, AMD Ryzen 9, 16GB RAM, 1TB SSD, NVIDIA GeForce RTX 3060, Eclipse Gray',
      price: '149990',
    },
    {
      id: 33,
      category: 'laptops',
      title: "Microsoft Surface Laptop 4",
      imgSrc: '/img/microsoft-surface.webp',
      amazonLink: 'https://amzn.to/3ZL1wIT',
      description: 'Microsoft Surface Laptop 4 13.5-inch, Intel Core i7, 16GB RAM, 512GB SSD, Windows 10, Platinum',
      price: '116999',
    },
    {
      id: 34,
      category: 'laptops',
      title: "Acer Predator Helios 300",
      imgSrc: '/img/acer-predator.webp',
      amazonLink: 'https://amzn.to/3RWNSv8',
      description: 'Acer Predator Helios 300 15.6-inch FHD Gaming Laptop, Intel Core i7, 16GB RAM, 512GB SSD, NVIDIA GeForce RTX 3060, Black',
      price: '109999',
    },
    {
      id: 35,
      category: 'laptops',
      title: "MSI GE76 Raider",
      imgSrc: '/img/msi-raider.jpg',
      amazonLink: 'https://amzn.to/3PDvK6O',
      description: 'MSI GE76 Raider 17.3-inch 4K Gaming Laptop, Intel Core i9, 32GB RAM, 1TB SSD, NVIDIA GeForce RTX 3080',
      price: '239999',
    },
    {
      id: 36,
      category: 'laptops',
      title: "Razer Blade 15",
      imgSrc: '/img/razer-blade.jpg',
      amazonLink: 'https://amzn.to/3rbQeGn',
      description: 'Razer Blade 15 15.6-inch OLED Laptop, Intel Core i7, 16GB RAM, 512GB SSD, NVIDIA GeForce RTX 3070',
      price: '179999',
    },
    {
      id: 37,
      category: 'laptops',
      title: "Apple MacBook Pro 16-inch",
      imgSrc: '/img/apple-16inc.webp',
      amazonLink: 'https://amzn.to/3DICrg4',
      description: 'Apple MacBook Pro 16-inch M1 Pro Chip, 16GB RAM, 512GB SSD, Retina Display, Silver',
      price: '189999',
    },
    {
      id: 38,
      category: 'laptops',
      title: "Dell Inspiron 15 5000",
      imgSrc: '/img/dell-5000.webp',
      amazonLink: 'https://amzn.to/3RxTSHe',
      description: 'Dell Inspiron 15 5000 15.6-inch FHD Laptop, Intel Core i5, 8GB RAM, 512GB SSD, Windows 10, Silver',
      price: '55999',
    },
    {
      id: 39,
      category: 'laptops',
      title: "HP Pavilion 14",
      imgSrc: '/img/hp-pavilion.webp',
      amazonLink: 'https://amzn.to/3r8M8Q1',
      description: 'HP Pavilion 14 14-inch Laptop, Intel Core i5, 8GB RAM, 512GB SSD, Windows 10, Natural Silver',
      price: '64999',
    },
    {
      id: 40,
      category: 'laptops',
      title: "Lenovo Legion 5 Pro",
      imgSrc: '/img/lenovo-legion.jpg',
      amazonLink: 'https://amzn.to/3L8wFfa',
      description: 'Lenovo Legion 5 Pro 15.6-inch Gaming Laptop, AMD Ryzen 7, 16GB RAM, 512GB SSD, NVIDIA GeForce RTX 3070',
      price: '109999',
    },


  ]